name: Build AppImage

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: latest

      - name: Install dependencies
        run: sudo apt-get install -y wget unzip libfuse2

      - name: Build AppImage
        run: |
          chmod +x build-appimage.sh
          ./build-appimage.sh

      - name: Upload AppImage to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.AppImage
